# Generated by Django 3.1 on 2020-08-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('college', models.CharField(default='', max_length=600)),
                ('gender', models.CharField(default='', max_length=700)),
                ('confession', models.TextField(default='', max_length=2500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
