# Generated by Django 3.1 on 2020-08-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='like',
        ),
        migrations.AddField(
            model_name='confession',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
    ]
