# Generated by Django 3.1 on 2020-09-01 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('reply', models.TextField(max_length=150)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confession.comment')),
            ],
        ),
    ]
